April deployment
christianrodriguez-8451/non_endemic_segmentations pull request #9
Opened 2024-04-10 21:37 UTC by christianrodriguez-8451

Here are a bunch of changes that I've been sitting on! I am pushing them now since we are deploying about 30 segments to PRISM.

2024-04-11 17:52 UTC, stevenmartz-8451 requested changes
Funlo methodology uses these date range weights so we need to keep these in the config:  DATE_RANGE_WEIGHTS = {4: 0.27, 3: 0.26, 2: 0.24, 1: 0.23}

2024-04-11 17:54 UTC, stevenmartz-8451 approved these changes

2024-04-11 18:05 UTC, stevenmartz-8451 requested changes
Please see my comments on products_embedding/config.py and toolbox/egress_prism_input_data.py.

2024-04-11 18:05 UTC, stevenmartz-8451 commented on toolbox/egress_prism_input_data.py
Recently Steve Ruwe pulled me into an issue where an audience wasn't meeting a Prism household minimum of 2 million.  We need to check with Brian Newell and team if we can set our threshold this low.  I know we keep getting conflicting information but I don't want us to cause user issue.

2024-04-12 16:39 UTC, christianrodriguez-8451 commented on toolbox/egress_prism_input_data.py
Is this threshold applied at audience or campaign level? What is the real threshold for an audience? For now, I set it back to 2 million. But call out on my end - a lot of the sensitive audiences are well below the 2 million count.

2024-04-26 13:55 UTC, stevenmartz-8451 commented on toolbox/egress_prism_input_data.py
I'm pretty sure it's at a campaign level.  Meaning if they choose one audience that's 1.5 MM then they will run into issues with the campaign.  But if they choose a 1.5 MM and a 2 MM audience giving them 3.5 MM for the campaign, they are fine.  I think Prism should check for this and notify the user.  I don't think our audiences should have that high of a limit.

2024-04-26 14:25 UTC, stevenmartz-8451 approved these changes
A lot of work has been done!  :)

2024-04-26 14:26 UTC, merged